### ISSUE TITLE
setState(...): Can only update a mounted or mounting component.

### ISSUE THREAD

**Issue by dominic3** [RafalFilipek/jsxfromhtml#2]
Get the following error when navigating between Views in a stack that utilize the JSXFromHtml component in react-native:

Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the JsxHtml component.

**Comment by RafalFilipek** [comment]
Hey @dominic3! 
Thank you for info. I've just released **0.0.8** with simple _isMounted_ check before setState. Can you check it? I hope it will solve this problem. If not, I'll have to ask you about more details how to reproduce this error.

**Comment by dominic3** [comment]
That took care of it Thanks!
